//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace milk_sales_manager.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string maNhanVien { get; set; }
        public string matKhau { get; set; }
        public string quyenHan { get; set; }
        public bool trangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
